language: python
services:
- docker
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - perl
      - libusb-1.0-0-dev
      - libudev-dev
      - libsecp256k1-0
matrix:
  include:
  - if: tag =~ .+
    os: osx
    language: ruby
    osx_image: xcode9.4
  - os: linux
    python: "3.6"
    dist: xenial
  - os: linux
    env:
    - ELECTRUM_MAINNET=true
    - APP_ANDROID_ARCH=armeabi-v7a
    python: "3.7"
    dist: xenial
  - if: tag =~ .+
    os: linux
    env:
    - ELECTRUM_MAINNET=false
    - APP_ANDROID_ARCH=armeabi-v7a
    python: "3.7"
    dist: xenial
  - if: tag =~ .+
    os: linux
    env:
    - ELECTRUM_MAINNET=true
    - APP_ANDROID_ARCH=arm64-v8a
    python: "3.7"
    dist: xenial
  - if: tag =~ .+
    os: linux
    env:
    - ELECTRUM_MAINNET=false
    - APP_ANDROID_ARCH=arm64-v8a
    python: "3.7"
    dist: xenial
before_install:
- source contrib/dash/travis/electrum_dash_version_env.sh
- echo electrum-dash version is $DASH_ELECTRUM_VERSION
- mkdir -p build && cp contrib/dash/travis/* ./build/
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/before_install-osx.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/before_install-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
      ./build/before_install-linux-apk.sh;
  fi
install:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      pip install tox tox-travis flake8;
  fi
script:
- if [[ -z $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]];then
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics; tox;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./build/travis-build-osx.sh ;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
      ./build/travis-build-linux.sh;
  fi
- if [[ -n $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then
     travis_wait 30 ./build/travis-build-linux-apk.sh;
  fi
deploy:
- provider: releases
  edge: false
  api_key:
    secure: xQA01OqAi24HUr8ByNyY9gX7tQi5wfTm149nGyNy2drn+n87J0VR21sM0pYAov7KQXO9kmrgAEtsoItGxPH3WsmMVmZzVYQVQu3Z9YnbEliAH0LWzEhM0aMYnKhG+dALMbuogbA3uCS4alFy18Pj7O9qaj9tZTHj215fDhnge9tqbcmHNTlccLYWesSwi+5bzd4r5rYSGtLRIbXZmhH558SLoGwxKDs5Orwcf6i7fNpNLy+FLBaqU3FY1UxhtR80b0KFrk7QuxxTVFcO8D4ZtLYqpe5ebhDnUgQz5ypKWw1uXdUsVn8c3vy7XdmeysP3sFr/N4dvdRJfjZW71/4GGB7CqAZLQqM/RLTQxKrhpyXKJInukx9AATWCShm3QxhnkLDpIH0940VyEak4SChM6LlszZMJNb9CqrB0G72x9XoA9sRbBkH2mOwZa8LMO0xiYO/p1x+l8AKmLZCFrFYxsQTNqnhA73q9Z75LXyqzoukLZUAeJJINZBiYfxoF/vuchIk6n0pjwCeWIXb1nfJjhiZ4nRfJE4KktlOwhavdnQs2hJcQHgphfOdp4h+nfDYi+nz1ZbFMVHeAUQI0f5FBm1iBsYQoeTe7VTm+tXiQ5Pebf04yGzrYsH1vTTuYHRQHT6255S9kX469mpv2YWren70B6oXxUAlzMEOWLzNvvJM=
  file:
  - build/electrum-dash/dist/Dash-Electrum-$DASH_ELECTRUM_VERSION-macosx.dmg
  on:
    repo: zebra-lucky/electrum-dash-old
    tags: true
    condition: "$TRAVIS_OS_NAME = osx"
- provider: releases
  edge: false
  api_key:
    secure: xQA01OqAi24HUr8ByNyY9gX7tQi5wfTm149nGyNy2drn+n87J0VR21sM0pYAov7KQXO9kmrgAEtsoItGxPH3WsmMVmZzVYQVQu3Z9YnbEliAH0LWzEhM0aMYnKhG+dALMbuogbA3uCS4alFy18Pj7O9qaj9tZTHj215fDhnge9tqbcmHNTlccLYWesSwi+5bzd4r5rYSGtLRIbXZmhH558SLoGwxKDs5Orwcf6i7fNpNLy+FLBaqU3FY1UxhtR80b0KFrk7QuxxTVFcO8D4ZtLYqpe5ebhDnUgQz5ypKWw1uXdUsVn8c3vy7XdmeysP3sFr/N4dvdRJfjZW71/4GGB7CqAZLQqM/RLTQxKrhpyXKJInukx9AATWCShm3QxhnkLDpIH0940VyEak4SChM6LlszZMJNb9CqrB0G72x9XoA9sRbBkH2mOwZa8LMO0xiYO/p1x+l8AKmLZCFrFYxsQTNqnhA73q9Z75LXyqzoukLZUAeJJINZBiYfxoF/vuchIk6n0pjwCeWIXb1nfJjhiZ4nRfJE4KktlOwhavdnQs2hJcQHgphfOdp4h+nfDYi+nz1ZbFMVHeAUQI0f5FBm1iBsYQoeTe7VTm+tXiQ5Pebf04yGzrYsH1vTTuYHRQHT6255S9kX469mpv2YWren70B6oXxUAlzMEOWLzNvvJM=
  file:
  - build/electrum-dash/dist/Dash-Electrum-$DASH_ELECTRUM_VERSION.tar.gz
  - build/electrum-dash/dist/Dash-Electrum-$DASH_ELECTRUM_VERSION.zip
  - build/electrum-dash/dist/Dash-Electrum-$DASH_ELECTRUM_VERSION-x86_64.AppImage
  - build/electrum-dash/dist/Dash-Electrum-$DASH_ELECTRUM_VERSION-setup-win32.exe
  - build/electrum-dash/dist/Dash-Electrum-$DASH_ELECTRUM_VERSION-setup-win64.exe
  - build/electrum-dash/bin/Electrum_DASH-$DASH_ELECTRUM_APK_VERSION-$APP_ANDROID_ARCH-release-unsigned.apk
  - build/electrum-dash/bin/Electrum_DASH_Testnet-$DASH_ELECTRUM_APK_VERSION-$APP_ANDROID_ARCH-release-unsigned.apk
  on:
    repo: zebra-lucky/electrum-dash-old
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
